{% set name = "Markdown" %}
{% set version = "3.1" %}
{% set sha256 = "fc4a6f69a656b8d858d7503bda633f4dd63c2d70cf80abdc6eafa64c4ae8c250" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  entry_points:
    - markdown_py = markdown.__main__:run

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - markdown
    - markdown.extensions
  commands:
    - markdown_py -h

about:
  home: https://pythonhosted.org/Markdown/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Python implementation of Markdown.'
  description: |
    This is a Python implementation of John Gruber’s Markdown. It is almost
    completely compliant with the reference implementation, though there are a
    few very minor differences.
  doc_url: http://pythonhosted.org/Markdown/
  dev_url: https://github.com/Python-Markdown/markdown

extra:
  recipe-maintainers:
    - dougalsutherland
