# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZYTlXOn+1x76Q6OcB9LmHZOfozZc5MXUPYIeeJNszHjTMuY24hszOXf+b0eigIiHBdqlff09sf1BNwkR7KeU9AcXiamQJ862D8s0bDN8GnAgVihbGGAX22kd7+i4GOVCvTUivvohkykMTo0Ymg8BKNhHl6sEAycfMZjmxizoocbB/I59LxSspUE956ou/BvZp1i1ZcHkuzpi1eNrvgaqiSOoPhG8LPXLez4UndpGaise73sA5QiVdxquYt+YE3/OmD5N5jPQdboi16T/ezm9UH03nwD9YZnsXsJn/1sPN7gNnMwY93d8m7H+o0L9oDoUnnQEE3DLDt3d3FiABkK3yubwhoiUW1RNIthZzKQ+tQhrjfv6kDGfcXnVx5tdKGSjYYXBhCzI6fj5HlNYzU86SL59Bk0jAWSt7Gyx6XgyzzfSzasVcICo471QTj+CB7xAjdR5UQVuczCvUO+ILroI3+DH1mMIyXyKAArNaY0dg9r0cmX7btJTDaQ7tTmAeAMPBDh7tpKgpwBq9FoznVKiikJL4z71P60X3W29agZPF+1hiLTtLTAwSQeMQd4FiRrVmgFiAXQ2ibao490G7HTwaVaPGA3IrNNjYFd9qfx6zSxwXKJ+k6FIx8ibH0LxQxcFvHq3pmlZSPOlDXPLX1fi23OmOkRYS8F4JKS25gV25L8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
